### ISSUE TITLE
Map shows as grey when using phonegap

### ISSUE THREAD

**Issue by robico** [triceam/Fresh-Food-Finder#3]
I've put this into a PhoneGap app for testing but the maps show up as grey when I use the app. When I use the code locally on my machine, the maps display fine. I haven't changed any of the code. Any ideas how to fix this and what is causing the problem?

**Comment by triceam** [comment]
Your probably just need to whitelist the domain for the map tiles.  See more info about domain whitelisting here: http://docs.phonegap.com/en/edge/guide_appdev_whitelist_index.md.html
